[package]
name = "nazuna"
version = "0.1.2"
edition = "2024"
description = "The no-nonsense WireGuard VPN manager. Minimalist, JSON-backed, and instantly ready. 🩸"
repository = "https://github.com/denisstrizhkin/nazuna"
license = "MIT"
keywords = ["config", "management", "vpn", "wg", "wireguard"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5", features = ["derive", "env"] }
ipnet = { version = "2.11.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
