use anyhow::{Context, Result};
use ipnet::Ipv4Net;
use serde::{Deserialize, Serialize};
use std::{
    io::{self, Write},
    net::Ipv4Addr,
    path::Path,
};

use crate::cmd;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct User {
    pub name: String,
    pub ip: Ipv4Addr,
    pub priv_key: String,
    pub pub_key: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Config {
    users: Vec<User>,
    server_pub_key: String,
    server_priv_key: String,
    server_net: Ipv4Net,
    client_dns: Option<Ipv4Addr>,
    endpoint_ip: Ipv4Addr,
    endpoint_port: u16,
    external_interface: String,
    wg_interface: String,
}

impl Config {
    pub fn try_new(
        endpoint_ip: Ipv4Addr,
        endpoint_port: u16,
        client_dns: Option<Ipv4Addr>,
        server_net: Ipv4Net,
        external_interface: String,
        wg_interface: String,
    ) -> Result<Self> {
        let priv_key = cmd::genkey().context("Failed to generate private key")?;
        let pub_key = cmd::pubkey(&priv_key).context("Failed to generate public key")?;
        Ok(Self {
            users: vec![],
            server_priv_key: priv_key,
            server_pub_key: pub_key,
            endpoint_ip,
            endpoint_port,
            client_dns,
            server_net,
            external_interface,
            wg_interface,
        })
    }

    pub fn open<P: AsRef<Path>>(path: P) -> Result<Self> {
        let path = path.as_ref();
        let file = std::fs::File::open(path)
            .with_context(|| format!("Failed to open database file {}", path.display()))?;
        serde_json::from_reader(file).context("Failed to parse database JSON")
    }

    pub fn save<P: AsRef<Path>>(&self, path: P) -> Result<()> {
        let path = path.as_ref();
        let file = std::fs::File::create(path)
            .with_context(|| format!("Failed to create database file {}", path.display()))?;
        serde_json::to_writer_pretty(file, self).context("Failed to serialize database to JSON")
    }

    pub fn get_wg_interface(&self) -> &str {
        &self.wg_interface
    }

    pub fn get_users(&self) -> &[User] {
        &self.users
    }

    pub fn add_user(&mut self, name: String) -> Result<User> {
        let ip = self
            .find_available_ip()
            .with_context(|| format!("No available IP addresses in subnet {}", self.server_net))?;
        let priv_key = cmd::genkey().context("Failed to generate user private key")?;
        let pub_key = cmd::pubkey(&priv_key).context("Failed to generate user public key")?;
        let user = User {
            name,
            ip,
            priv_key,
            pub_key,
        };
        self.users.push(user.clone());
        Ok(user)
    }

    pub fn find_user(&self, name: &str) -> Option<&User> {
        self.users.iter().find(|u| u.name == name)
    }

    pub fn remove_user(&mut self, name: &str) -> Option<User> {
        let idx = self.users.iter().position(|u| u.name == name);
        idx.map(|idx| self.users.swap_remove(idx))
    }

    pub fn find_available_ip(&self) -> Option<Ipv4Addr> {
        let taken_ips = self
            .users
            .iter()
            .map(|u| u.ip)
            .collect::<std::collections::HashSet<_>>();
        let server_ip = self.server_net.addr();
        self.server_net
            .hosts()
            .find(|ip| *ip != server_ip && !taken_ips.contains(ip))
    }

    pub fn write_wg_conf<W: Write>(&self, w: &mut W) -> io::Result<()> {
        writeln!(w, "# This config is autogenerated and managed by nazuna.")?;
        writeln!(w, "# Manual changes will be overwritten.")?;
        writeln!(w, "[Interface]")?;
        writeln!(w, "Address = {}", self.server_net)?;
        writeln!(w, "SaveConfig = false")?;
        writeln!(w, "PrivateKey = {}", self.server_priv_key)?;
        writeln!(w, "ListenPort = {}", self.endpoint_port)?;
        writeln!(w, "PreUp = sysctl -w net.ipv4.ip_forward=1")?;
        writeln!(
            w,
            "PostUp = iptables -A FORWARD -i {} -j ACCEPT; iptables -t nat -A POSTROUTING -o {} -j MASQUERADE",
            self.wg_interface, self.external_interface
        )?;
        writeln!(
            w,
            "PostDown = iptables -D FORWARD -i {} -j ACCEPT; iptables -t nat -D POSTROUTING -o {} -j MASQUERADE",
            self.wg_interface, self.external_interface
        )?;
        for user in &self.users {
            writeln!(w, "\n[Peer]")?;
            writeln!(w, "# Name: {}", user.name)?;
            writeln!(w, "PublicKey = {}", user.pub_key)?;
            writeln!(w, "AllowedIPs = {}/32", user.ip)?;
        }
        Ok(())
    }

    pub fn write_client_conf<W: Write>(&self, w: &mut W, user: &User) -> io::Result<()> {
        writeln!(w, "[Interface]")?;
        writeln!(w, "PrivateKey = {}", user.priv_key)?;
        writeln!(w, "Address = {}/32", user.ip)?;
        if let Some(dns) = self.client_dns {
            writeln!(w, "DNS = {dns}")?;
        }
        writeln!(w, "[Peer]")?;
        writeln!(w, "PublicKey = {}", self.server_pub_key)?;
        writeln!(w, "Endpoint = {}:{}", self.endpoint_ip, self.endpoint_port)?;
        writeln!(w, "AllowedIPs = 0.0.0.0/0")?;
        writeln!(w, "PersistentKeepalive = 25")
    }
}
