use anyhow::{Context, Result};
use ipnet::Ipv4Net;
use serde::{Deserialize, Serialize};
use std::{
    io::{self, Write},
    net::Ipv4Addr,
    path::Path,
};

use crate::cmd::KeyGenerator;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct User {
    pub name: String,
    pub ip: Ipv4Addr,
    pub priv_key: String,
    pub pub_key: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Config {
    users: Vec<User>,
    server_pub_key: String,
    server_priv_key: String,
    server_net: Ipv4Net,
    client_dns: Option<Ipv4Addr>,
    endpoint_ip: Ipv4Addr,
    endpoint_port: u16,
    external_interface: String,
    wg_interface: String,
}

impl Config {
    pub fn try_new<G: KeyGenerator>(
        endpoint_ip: Ipv4Addr,
        endpoint_port: u16,
        client_dns: Option<Ipv4Addr>,
        server_net: Ipv4Net,
        external_interface: String,
        wg_interface: String,
        key_gen: &G,
    ) -> Result<Self> {
        let priv_key = key_gen
            .gen_key()
            .context("Failed to generate private key")?;
        let pub_key = key_gen
            .pub_key(&priv_key)
            .context("Failed to generate public key")?;
        Ok(Self {
            users: vec![],
            server_priv_key: priv_key,
            server_pub_key: pub_key,
            endpoint_ip,
            endpoint_port,
            client_dns,
            server_net,
            external_interface,
            wg_interface,
        })
    }

    pub fn open<P: AsRef<Path>>(path: P) -> Result<Self> {
        let path = path.as_ref();
        let file = std::fs::File::open(path)
            .with_context(|| format!("Failed to open database file {}", path.display()))?;
        serde_json::from_reader(file).context("Failed to parse database JSON")
    }

    pub fn save<P: AsRef<Path>>(&self, path: P) -> Result<()> {
        let path = path.as_ref();
        let file = std::fs::File::create(path)
            .with_context(|| format!("Failed to create database file {}", path.display()))?;
        serde_json::to_writer_pretty(file, self).context("Failed to serialize database to JSON")
    }

    pub fn get_wg_interface(&self) -> &str {
        &self.wg_interface
    }

    pub fn get_users(&self) -> &[User] {
        &self.users
    }

    pub fn add_user<G: KeyGenerator>(&mut self, name: String, key_gen: &G) -> Result<User> {
        let ip = self
            .find_available_ip()
            .with_context(|| format!("No available IP addresses in subnet {}", self.server_net))?;
        let priv_key = key_gen
            .gen_key()
            .context("Failed to generate user private key")?;
        let pub_key = key_gen
            .pub_key(&priv_key)
            .context("Failed to generate user public key")?;
        let user = User {
            name,
            ip,
            priv_key,
            pub_key,
        };
        self.users.push(user.clone());
        Ok(user)
    }

    pub fn find_user(&self, name: &str) -> Option<&User> {
        self.users.iter().find(|u| u.name == name)
    }

    pub fn remove_user(&mut self, name: &str) -> Option<User> {
        let idx = self.users.iter().position(|u| u.name == name);
        idx.map(|idx| self.users.swap_remove(idx))
    }

    pub fn find_available_ip(&self) -> Option<Ipv4Addr> {
        let taken_ips = self
            .users
            .iter()
            .map(|u| u.ip)
            .collect::<std::collections::HashSet<_>>();
        let server_ip = self.server_net.addr();
        self.server_net
            .hosts()
            .find(|ip| *ip != server_ip && !taken_ips.contains(ip))
    }

    pub fn write_wg_conf<W: Write>(&self, w: &mut W) -> io::Result<()> {
        writeln!(w, "# This config is autogenerated and managed by nazuna.")?;
        writeln!(w, "# Manual changes will be overwritten.")?;
        writeln!(w, "[Interface]")?;
        writeln!(w, "Address = {}", self.server_net)?;
        writeln!(w, "SaveConfig = false")?;
        writeln!(w, "PrivateKey = {}", self.server_priv_key)?;
        writeln!(w, "ListenPort = {}", self.endpoint_port)?;
        writeln!(w, "PreUp = sysctl -w net.ipv4.ip_forward=1")?;
        writeln!(
            w,
            "PostUp = iptables -A FORWARD -i {} -j ACCEPT; iptables -t nat -A POSTROUTING -o {} -j MASQUERADE",
            self.wg_interface, self.external_interface
        )?;
        writeln!(
            w,
            "PostDown = iptables -D FORWARD -i {} -j ACCEPT; iptables -t nat -D POSTROUTING -o {} -j MASQUERADE",
            self.wg_interface, self.external_interface
        )?;
        for user in &self.users {
            writeln!(w, "\n[Peer]")?;
            writeln!(w, "# Name: {}", user.name)?;
            writeln!(w, "PublicKey = {}", user.pub_key)?;
            writeln!(w, "AllowedIPs = {}/32", user.ip)?;
        }
        Ok(())
    }

    pub fn write_client_conf<W: Write>(&self, w: &mut W, user: &User) -> io::Result<()> {
        writeln!(w, "[Interface]")?;
        writeln!(w, "PrivateKey = {}", user.priv_key)?;
        writeln!(w, "Address = {}/32", user.ip)?;
        if let Some(dns) = self.client_dns {
            writeln!(w, "DNS = {dns}")?;
        }
        writeln!(w, "[Peer]")?;
        writeln!(w, "PublicKey = {}", self.server_pub_key)?;
        writeln!(w, "Endpoint = {}:{}", self.endpoint_ip, self.endpoint_port)?;
        writeln!(w, "AllowedIPs = 0.0.0.0/0")?;
        writeln!(w, "PersistentKeepalive = 25")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cmd::KeyGenerator;
    use std::str::FromStr;

    struct MockKeyGenerator;

    impl KeyGenerator for MockKeyGenerator {
        fn gen_key(&self) -> Result<String> {
            Ok("MOCK_PRIVATE_KEY".to_string())
        }

        fn pub_key(&self, _priv_key: &str) -> Result<String> {
            Ok("MOCK_PUBLIC_KEY".to_string())
        }
    }

    fn create_test_config() -> Config {
        let server_net: Ipv4Net = "10.0.0.1/24".parse().unwrap();
        Config::try_new(
            Ipv4Addr::LOCALHOST,
            51820,
            Some(Ipv4Addr::new(8, 8, 8, 8)),
            server_net,
            "eth0".to_string(),
            "wg0".to_string(),
            &MockKeyGenerator,
        )
        .expect("Failed to create config")
    }

    #[test]
    fn test_config_initialization() {
        let config = create_test_config();
        assert_eq!(config.users.len(), 0);
        assert_eq!(config.server_priv_key, "MOCK_PRIVATE_KEY");
        assert_eq!(config.server_pub_key, "MOCK_PUBLIC_KEY");
        assert_eq!(config.wg_interface, "wg0");
    }

    #[test]
    fn test_add_user() {
        let mut config = create_test_config();
        let user = config
            .add_user("test_user".to_string(), &MockKeyGenerator)
            .expect("Failed to add user");

        assert_eq!(user.name, "test_user");
        assert_eq!(user.priv_key, "MOCK_PRIVATE_KEY");
        assert_eq!(user.pub_key, "MOCK_PUBLIC_KEY");
        // First available IP after 10.0.0.1 (server) should be 10.0.0.2
        assert_eq!(user.ip, Ipv4Addr::from_str("10.0.0.2").unwrap());

        assert_eq!(config.users.len(), 1);
    }

    #[test]
    fn test_add_multiple_users() {
        let mut config = create_test_config();
        let user1 = config
            .add_user("user1".to_string(), &MockKeyGenerator)
            .unwrap();
        let user2 = config
            .add_user("user2".to_string(), &MockKeyGenerator)
            .unwrap();

        assert_eq!(user1.ip, Ipv4Addr::from_str("10.0.0.2").unwrap());
        assert_eq!(user2.ip, Ipv4Addr::from_str("10.0.0.3").unwrap());
        assert_eq!(config.users.len(), 2);
    }

    #[test]
    fn test_remove_user() {
        let mut config = create_test_config();
        config
            .add_user("user1".to_string(), &MockKeyGenerator)
            .unwrap();
        config
            .add_user("user2".to_string(), &MockKeyGenerator)
            .unwrap();

        let removed = config.remove_user("user1");
        assert!(removed.is_some());
        assert_eq!(removed.unwrap().name, "user1");
        assert_eq!(config.users.len(), 1);
        assert_eq!(config.users[0].name, "user2");

        let removed_again = config.remove_user("user1");
        assert!(removed_again.is_none());
    }

    #[test]
    fn test_ip_reuse() {
        let mut config = create_test_config();
        config
            .add_user("user1".to_string(), &MockKeyGenerator)
            .unwrap();
        let _user2 = config
            .add_user("user2".to_string(), &MockKeyGenerator)
            .unwrap(); // 10.0.0.3

        config.remove_user("user1"); // frees 10.0.0.2

        let user3 = config
            .add_user("user3".to_string(), &MockKeyGenerator)
            .unwrap();
        // user3 should get 10.0.0.2 because it's the first available
        // Note: find_available_ip implementation iterates hosts, so it finds the first free one.
        assert_eq!(user3.ip, Ipv4Addr::from_str("10.0.0.2").unwrap());
        assert_eq!(config.users.len(), 2);
    }
}
